
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall_pms?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: mall-product

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      # 主键自增
      id-type: auto

server:
  port: 10000